// <auto-generated />
using System;
using DataLayer_NRE_Portal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer_NRE_Portal.Migrations
{
    [DbContext(typeof(NrePortalContext))]
    [Migration("20251105161938_InitLocalDb")]
    partial class InitLocalDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("DataLayer_NRE_Portal.Models.InstallationBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AnnualProductionKWh")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("CommissioningDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnergyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("InstalledCapacityKW")
                        .HasColumnType("REAL");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCrs")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SourceX")
                        .HasColumnType("REAL");

                    b.Property<double?>("SourceY")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Latitude", "Longitude");

                    b.HasIndex("Region", "EnergyType");

                    b.ToTable("Installations", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DataLayer_NRE_Portal.Models.ProductionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnergyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ProductionKWh")
                        .HasColumnType("REAL");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProductionSummaries");
                });

            modelBuilder.Entity("DataLayer_NRE_Portal.Models.PrivateInstallation", b =>
                {
                    b.HasBaseType("DataLayer_NRE_Portal.Models.InstallationBase");

                    b.Property<double?>("AreaM2")
                        .HasColumnType("REAL");

                    b.Property<int?>("Azimuth")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EstimatedKWh")
                        .HasColumnType("REAL");

                    b.Property<string>("IntegrationType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LengthM")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationText")
                        .HasColumnType("TEXT");

                    b.Property<string>("PvCellType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoofSlope")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("WidthM")
                        .HasColumnType("REAL");

                    b.ToTable("PrivateInstallations", (string)null);
                });

            modelBuilder.Entity("DataLayer_NRE_Portal.Models.PublicInstallation", b =>
                {
                    b.HasBaseType("DataLayer_NRE_Portal.Models.InstallationBase");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Municipality")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceRef")
                        .HasColumnType("TEXT");

                    b.ToTable("PublicInstallations", (string)null);
                });

            modelBuilder.Entity("DataLayer_NRE_Portal.Models.PrivateInstallation", b =>
                {
                    b.HasOne("DataLayer_NRE_Portal.Models.InstallationBase", null)
                        .WithOne()
                        .HasForeignKey("DataLayer_NRE_Portal.Models.PrivateInstallation", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataLayer_NRE_Portal.Models.PublicInstallation", b =>
                {
                    b.HasOne("DataLayer_NRE_Portal.Models.InstallationBase", null)
                        .WithOne()
                        .HasForeignKey("DataLayer_NRE_Portal.Models.PublicInstallation", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
